[workspace]
resolver = "2"

members = ["generator", "ast", "testing", "tonic-test"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[workspace.dependencies]
indexmap = "2.6"
