[package]
name = "tarnik-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tarnik = { path = "../generator" }
tarnik-ast = { path = "../ast" }
anyhow = "1.0"
tempfile = "3.8"
assert_cmd = "2.0"
predicates = "3.0"
